modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "improvedmapcolors"
version = "${version}"
displayName = "ImprovedMapColors"
authors = "gamma_02, Gneiss Name, Grassy"
description = '''

'''
logoFile = "icon.png"

[[dependencies.improvedmapcolors]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.improvedmapcolors]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.8]"
ordering = "NONE"
side = "BOTH"

[[dependencies.improvedmapcolors]]
modId = "architectury"
type = "required"
versionRange = "[13.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "improvedmapcolors.mixins.json"

[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file="META-INF/accesstransformer.cfg"
